### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by alice-i-cecile** [drakmaniso/bevy_pixel_camera#13]
I would really like to use this crate, but the license is unclear. Ideally, this would be licensed under MIT + Apache 2.0 so it can eventually be upstreamed :)

**Comment by alice-i-cecile** [comment]
Ah, the README mentions it's licensed that way, but there's no LICENSE file! Well, that should be an easy fix. Thanks for making this!

**Comment by alice-i-cecile** [comment]
And your Cargo.toml is already set up correctly. Great!

**Comment by drakmaniso** [comment]
Oops, I don't know how I could forgot to include the license files... Thanks for noticing!
