### ISSUE TITLE
Render texture.

### ISSUE THREAD

**Issue by Vixeliz** [drakmaniso/bevy_pixel_camera#24]
Hey! So I was originally going to fork this and add on some things initially my scope was high but now I realize it may be better to upstream. Are you interested in adding an option for a render texture version since each way has advantages and disadvantages? I have a simple version mostly working at my repo bevy_pixel. I'd love to make a pr if you are interested. Separating out the two camera types into their own files. Let me know what you think. Awesome work :)

**Comment by Vixeliz** [comment]
I've decided I'm gonna keep my pseudo fork but feel free to still look If u are interested in this.

**Comment by drakmaniso** [comment]
Sorry for the late answer... I agree that it's probably better to keep both approaches separated. Also I don't have much time at the moment to work on bevy related stuff, so I'd prefer to keep this crate simple. But thanks for the suggestion!
