### ISSUE TITLE
Use Viewport from Bevy 0.8 instead of sprites to implement screen borders

### ISSUE THREAD

**Issue by drakmaniso** [drakmaniso/bevy_pixel_camera#9]
Bevy 0.8 added a `Viewport` to each `Camera`, which should be enough to implement the borders around the desired resolution.

**Comment by Vixeliz** [comment]
If you want this it's mostly working on my repo https://github.com/vixeliz/bevy_vinox_pixel. Under src/camera/scaled.rs. It should at least get you started. :)

**Comment by drakmaniso** [comment]
Thanks, I'll take a look!

**Comment by drakmaniso** [comment]
Fixed by #28
